#
# Copyright (c) 2004-2018, University of Oslo
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# Neither the name of the HISP project nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO PROGRAM_STAGE_EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

server:
  port: 8081

spring:
  flyway:
    locations: @db.flyway.locations@
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
    hikari:
      maximum-pool-size: 50
  artemis:
    embedded:
      enabled: true
      server-id: 1
      persistent: true
      data-directory: ${dhis2.home}/services/fhir-adapter/artemis
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100000
        timeout:
          enabled: false
      circuitBreaker:
        enabled: true
      fallback:
        enabled: true

dhis2.fhir-adapter:
  endpoint:
    url: @dhis2.url@
    api-version: @dhis2.apiVersion@
    system-authentication:
      username: @dhis2.username@
      password: @dhis2.password@
  security:
    authorities:
      administration:
      - F_SYSTEM_SETTING
      code-mapping:
      - F_SYSTEM_SETTING
      data-mapping:
      - F_SYSTEM_SETTING
  cache:
    metadata:
      type: caffeine
      caffeine:
        spec: expireAfterAccess=60s,maximumSize=10000
      redis:
        time-to-live: 60s
        key-prefix: fhir-adapter:metadata
    dhis:
      type: caffeine
      caffeine:
        spec: expireAfterAccess=120s,maximumSize=10000
      redis:
        time-to-live: 120s
        key-prefix: fhir-adapter:dhis
    fhir:
      type: caffeine
      caffeine:
        spec: expireAfterAccess=500s,maximumSize=10000
      redis:
        time-to-live: 500s
        key-prefix: fhir-adapter:fhir
  remote:
    processor:
      max-search-count: 10000
      max-processed-age-minutes: 2880
    web-hook-request-queue:
      queue-name: jms.queue.remoteWebHookRequestQueue
      listener:
        concurrency: 1-5
      embedded-address-settings:
        max-delivery-attempts: 100
        redelivery-delay: 30000
        redelivery-multiplier: 3.0
        max-redelivery-delay: 1800000
  repository:
    fhir-resource-dl-queue:
      queue-name: jms.queue.remoteFhirResourceDlQueue
      embedded-address-settings:
        expiry-delay: 2419200000
    fhir-resource-queue:
      queue-name: jms.queue.remoteFhirResourceQueue
      listener:
        concurrency: 1-10
      embedded-address-settings:
        dead-letter-address: jms.queue.remoteFhirResourceDlQueue
        max-delivery-attempts: 100
        redelivery-delay: 30000
        redelivery-multiplier: 3.0
        max-redelivery-delay: 1800000
  transformation:
    script-engine-name: nashorn
